### ISSUE TITLE
Missing support for username-only authentication

### ISSUE THREAD

**Issue by paulmillar** [ezhov-evgeny/webdav-client-python-3#123]
From inspecting the code, it seems that both the `webdav_login` and `webdav_password` options must be set to a non-empty string before the client will attempt HTTP basic authentication in its WebDAV requests.  If either option is missing or an empty string then the client will not use HTTP basic authentication.

(For me, this requirement wasn't particularly clear from the documentation.)

[ownCloud](https://owncloud.com/) and [NextCloud](https://nextcloud.com/) are both open-source sync-and-share software.  When deployed, they allow the users to create shares.  Shares are somewhat similar to directories and contain files that may be accessed by external people (those who do not already have an account).  Shares may be private (requiring a shared secret) or public (requiring no authentication).  In addition to providing access to public shared via their respective Web-based GUI, the shares may be accessed via WebDAV.  This is true for both [ownCloud](https://doc.owncloud.com/webui/next/classic_ui/files/access_webdav.html#accessing-public-link-shares-over-webdav) and [NextCloud](https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html#accessing-public-shares-over-webdav).

Both ownCloud and NextCloud use a common scheme for handling WebDAV access to shares; specifically, the WebDAV URL is constant (usually in the form `https://cloud.example.org/public.oho/webdav`).  The share ID is passed as the username during HTTP basic authentication.  For public shares (ones requiring no password) the HTTP basic authentication should contain an empty password.

It is currently not possible to access public shares, as it is currently not possible to trigger HTTP basic authentication with only a username (see above).

There is a work-around.  The Client has a requests session object, which may be manipulated directly; e.g.,

```python
from webdav3.client import Client

client = Client({'webdav_hostname': 'https://cloud.example.org/public.php/webdav'})
client.session.auth = (share_id, "")
```

Nevertheless, I think it would be a good idea if the client could trigger HTTP basic authentication with only the username.

**Comment by pataquets** [comment]
Duplicate of #111?

**Comment by paulmillar** [comment]
Thanks @pataquets .  I think you're right: this is a dup of #111.  I'll close this issue in favour of that one.
