### ISSUE TITLE
Is webdavclient3 v0.13 multiprocess safe ?

### ISSUE THREAD

**Issue by macdoor** [ezhov-evgeny/webdav-client-python-3#28]
I just upgrade to version 0.13 with no code modified. 
raise error 
ERROR - name 'hostname' is not defined 

When I downgrade to 0.12. everything is okay. I am using webdavclient3 in multiprocessing.pool. Is webdavclient3 v0.13 multiprocess safe ?

**Comment by ezhov-evgeny** [comment]
@macdoor try new version 0.14, some of the issues were fixed there.

**Comment by ezhov-evgeny** [comment]
@macdoor have you tried with new version?

**Comment by fbuccioni** [comment]
I'm using webdavclient3 0.13 in multiprocess without problem, because it makes a request on every method call.

Maybe you need to print the errors inside a subprocess, [I use a decorator to force the exception to be printed inside a worker](https://stackoverflow.com/a/59489898/742249).

**Comment by ezhov-evgeny** [comment]
@macdoor Just released 3.14 try this version
