### ISSUE TITLE
Problem with initial connect in release 0.14

### ISSUE THREAD

**Issue by fbuccioni** [ezhov-evgeny/webdav-client-python-3#30]
I have the following problem, I'm connecting to a propietary WebDAV service, but the service is in a path that wasn't root and root directory answers a 404 error.

In the 0.14 release the client in the `__init__` function make a test connection to the root
https://github.com/ezhov-evgeny/webdav-client-python-3/blob/7db1cfd27415383507f937c8936cf02ce2ee1100/webdav3/client.py#L156

In my special case, it raises a NotFound error when connect, so maybe is possibly to give a root path or a config to not test the connection at start.

Thanks!

**Comment by ezhov-evgeny** [comment]
@fbuccioni I have an idea of how to resolve and don't break other functionality I'm fixing it soon

**Comment by ezhov-evgeny** [comment]
@fbuccioni It is fixed in develop branch, soon it will be released

**Comment by ezhov-evgeny** [comment]
@fbuccioni Just released 3.14 try this version
