### ISSUE TITLE
Not all webdav servers implement HEAD on folders

### ISSUE THREAD

**Issue by Phaiax** [ezhov-evgeny/webdav-client-python-3#31]
Stackoverflow is not in unison about the question if webdav servers must implement the HEAD request on folders: https://stackoverflow.com/questions/16578345/should-webdav-server-support-head-on-folders

Anyway, the webdav server in my Synology NAS does not implement HEAD on folders. It answers with status code 404 on the root folder and status code 403 on nested folders. If I do a PROPFIND on the same path it gives me information about the path.

(See https://gist.github.com/Phaiax/1b186336eb3c6d457705a1564ed112a4 for some curl tests
Edit: I tried it all with trailing `/` and without, the results were the same.)

This has the effect that I can't list folders because `list()` first checks if the folder exists:
```python
        if directory_urn.path() != Client.root and not self.check(directory_urn.path()):
            raise RemoteResourceNotFound(directory_urn.path())
```

Check uses the `HEAD` method on the folder, and that fails.

I propose that `list()` should call `is_dir()` instead of `check()`. Also, the `info` action should also set `Depth=0` instead of `Depth=1` in the header because the directory listing is not needed in the cases where the `info` action is used. Thirdly, document that not all servers support `check()` on folders, even if the RFC says otherwise.

Thanks, Daniel

**Comment by ezhov-evgeny** [comment]
@Phaiax I think I have a solution to resolve this issue, I'm planning to fix it as soon as possible

**Comment by ezhov-evgeny** [comment]
@Phaiax Just released 3.14 try this version

**Comment by hwiorn** [comment]
@ezhov-evgeny 
Did you test it on Synology WebDav server?
In my case, Both `GET` and `HEAD` on a directory show a 403 forbidden error always. 
I found that `GET` works at the files not directories on Synology.

**Comment by ezhov-evgeny** [comment]
@hwiorn Unfortunately I don't have Synology NAS for testing it. 
But 403 error means that the user doesn't have an access to that resource. Try to check:
- user permissions
- authorization method

**Comment by hwiorn** [comment]
@ezhov-evgeny Yeah, I understand. I have right permission because I have an admin privilege and I already checked other WebDav clients like cadaver, ubuntu file manager, iOS App, etc.. and python requests module to manipulating HTTP methods(GET, HEAD, PROPFIND, ..).  So I realized that `PROPFIND` works well on a directory in Synology NAS. But `GET` and `HEAD` don't work the directory.
