### ISSUE TITLE
Errors during simultaneous connections

### ISSUE THREAD

**Issue by pkarbovn** [ezhov-evgeny/webdav-client-python-3#34]
Situation:
Need to put single file into multiple accounts using webdav.

Implementation:
Connecting to accounts using threads (3-4). Each thread create client = Client(options)
and running small download to test connections. There are many clients so each 
thread is doing same operation but for different client (limit on 3-4 threads not saturate network link.)

Problem:
CopyThread::__copy_file [Thread-2]!(['Test_Client01_2020-01.zip'])
CopyThread::__copy_file [Thread-1]!(['Test_Client02_2020-01.zip'])
CopyThread::__copy_file [Thread-3]!(['Test_Client05_2020-01.zip'])
CopyThread::__copy_file [Thread-1]!(['Test_Client03_2020-01.zip'])
CopyThread::__copy_file [Thread-2]!(['Test_Client04_2020-01.zip'])
except CopyThread::__process_package [Thread-2]! Remote resource: / not found
CopyThread::__copy_file [Thread-3]!(['Test_Client07_2020-01.zip'])
CopyThread::__copy_file [Thread-1]!(['Test_Client08_2020-01.zip'])
except CopyThread::__process_package [Thread-1]! Remote resource: / not found
.......

My quick solution:
Move {root, session, timeout verify} from static class Client variables into local object variables
so they in __init__ function {self.root, self.session, self.timeout, self.verify}
This seems to solve my problem.

**Comment by ezhov-evgeny** [comment]
@pkarbovn I'm planning to fix as soon as possible, I guess it will be done at the end of January

**Comment by ezhov-evgeny** [comment]
@pkarbovn Just released 3.14 try this version
