### ISSUE TITLE
Client.move() не обрабатывает кириллицу при работе с NextCloud

### ISSUE THREAD

**Issue by sergushenkov** [ezhov-evgeny/webdav-client-python-3#40]
При работе с сервером NextCloud, если в названии файла или папки есть кириллица, то Client.move() или Сlient.clean() падают с ошибкой UnicodeEncodeError: 'latin-1' codec can't encode characters in position 52-55: ordinal not in range(256). При этом другие функции (.mkdir(), .info(), .list(), .download_file(), .upload_file()) работают нормально

**Comment by ezhov-evgeny** [comment]
@sergushenkov I will try to reproduce it and fix soon

**Comment by ezhov-evgeny** [comment]
@sergushenkov I have fixed it and merged in development will be published in version 3.14.1
