### ISSUE TITLE
Consider using <d:getcontenttype> to calculate is_dir

### ISSUE THREAD

**Issue by gwy15** [ezhov-evgeny/webdav-client-python-3#46]
Currently, `Urn` marks itself as a directory if and only if its href ends with a '/'. However, this may not apply to all webdav implementations. For example, the webdav provider I'm using currently ([link, chinese website](https://www.jianguoyun.com/)) returns `<d:response><d:href>` never ends with a `/`. Instead, it marks an item a directory using `<d:response><d:propstat><d:prop><d:getcontenttype>`  with text `httpd/unix-directory`. See demo response below.

```xml
<d:response>
    <d:href>/dav/(censored)</d:href>
    <d:propstat>
        <d:prop>
            <d:getlastmodified>Mon, 24 Feb 2020 02:29:02 GMT</d:getlastmodified>
            <d:getcontentlength>0</d:getcontentlength>
            <d:getetag />
            <d:owner>gwy15thu@gmail.com</d:owner>
            <d:current-user-privilege-set>
                <d:privilege>
                    <d:read />
                </d:privilege>
                <d:privilege>
                    <d:write />
                </d:privilege>
                <d:privilege>
                    <d:all />
                </d:privilege>
                <d:privilege>
                    <d:read_acl />
                </d:privilege>
                <d:privilege>
                    <d:write_acl />
                </d:privilege>
            </d:current-user-privilege-set>
            <d:getcontenttype>httpd/unix-directory</d:getcontenttype>
            <d:displayname>(censored)</d:displayname>
            <d:resourcetype>
                <d:collection />
            </d:resourcetype>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
</d:response>
```
I'm new to webdav protocol and not familier with its standard implementation. If it is a wrong implementation from the webdav provider, please let me known and I'll contact the site's custom. Many thanks.

**Comment by ezhov-evgeny** [comment]
@gwy15 I have investigated this issue, but not all implementations return content type for directories.
I will investigate the possible solution.
