### ISSUE TITLE
handle webdav_hostname tailing slash

### ISSUE THREAD

**Issue by alex-itboy** [ezhov-evgeny/webdav-client-python-3#49]
Hi, I am new to webdav, and I just spent hours to get client.list() to work, then I just find out that I have a tailing slash in config['webdav_hostname'] that makes me failed. It has a tailing slash because the URL from my service provider has it and I didn't think it matters until now. Should the library have the ability to handle tailing slash?

**Comment by ezhov-evgeny** [comment]
Hi @alex-itboy, I will include it in the next release

**Comment by alex-itboy** [comment]
Thank you very much.
