### ISSUE TITLE
Allow other Auth methods like NTLM

### ISSUE THREAD

**Issue by stefanvangastel** [ezhov-evgeny/webdav-client-python-3#54]
It looks like only basic auth is allowed form https://github.com/ezhov-evgeny/webdav-client-python-3/blob/develop/webdav3/client.py#L217 

Is it possible to allow other auth methods like NTLM, e.g.:

```python
client.session.auth = HttpNtlmAuth(username, password)
```

**Comment by matrixx567** [comment]
You have the same problem as described in #50.

**Comment by stefanvangastel** [comment]
Cool, so this wil be released soon? Thanks!

**Comment by ezhov-evgeny** [comment]
@stefanvangastel @matrixx567 It was released today in version 3.14.2
