### ISSUE TITLE
List return rootpath

### ISSUE THREAD

**Issue by huangganggui** [ezhov-evgeny/webdav-client-python-3#63]
When files is:
a
-b
-c
list('a') will return ['a', 'b', 'c']
When files is:
a
-a
-b
-c
list('a') will return ['a', 'b', 'c', 'a']

It makes me confused. i expect that it don't return the parent dir name.

**Comment by huangganggui** [comment]
Hi, I found the reason why it is return parent folder name.

When the webdav_hostname contain folder like `http://localhost:8585/webdav`, the list() will return a list contain folder
 
The reason is that client -> get_full_path() will not return '/webdav' but the href of wevdav response return it.

**Comment by ssdEw** [comment]
You should change, the options of Client constructor:

**Change this:**
```
options = {
    "webdav_hostname": "http://localhost:8585/webdav"
}
```

**by this:**
```
options = {
    "webdav_hostname": "http://localhost:8585",
    'webdav_root': 'webdav'
}
```
