### ISSUE TITLE
Unexpected/wrong behaviour in combination with nextcloud

### ISSUE THREAD

**Issue by Zapnuk** [ezhov-evgeny/webdav-client-python-3#65]
Is this library compatiple with nextcloud? I'm experiencing very odd+wrong behaviour. 

In the code below I first check for existing and non-existing directories and files. Afterwards I create a new directory and sync a single file.

Based on that test, every tested function doesn't work as I expect it to based on the readme,

- `check` returns always true for files and always false for directories. Except if the directory doesn' exist. In that case it returns true.
- `mkdir` returns true, indicating that the directory was created, but thats not the case (check with the nextcloud webview)
- `upload_sync` doesn't upload the file but also raises no error.

`

    def issue():
      c = {
          'webdav_hostname': config.nextcloud_url,
          'webdav_login':    config.username,
          'webdav_password': config.password
      }
      client = Client(c)

      # exists
      print('Check existing: expect 3x True')
      print(client.check('Photos'))
      print(client.check('Nextcloud.png'))
      print(client.check('Photos/Frog.jpg'))

      #doesn't exist
      print('Check non-existing: expect 3x False')
      print(client.check('test_Documents')) 
      print(client.check('test3.pdf')) 
      print(client.check('test_Photos/Frog.jpg'))

      # create
      r = client.mkdir('test_Documents')
      r2 = client.check('test_Documents')
      print('Add new dir: expect 2x True')
      print(r, r2)

      client.upload_sync(remote_path='test3.pdf', local_path='../test3.pdf')
      r3 = client.check('test3.pdf')
      print('Check sync file: expect True')
      print(r3)

      print('Check new dir, synced file')
      client = Client(c)
      r = client.check('test_Documents')
      r2 = client.check('test3.pdf')
      print('expect 2x True')
      print(r, r2)

Output:

    Check existing: expect 3x True
    False
    True
    True
    Check non-existing: expect 3x False
    True
    True
    True
    Add new dir: expect 2x True
    True True
    Check sync file: expect True
    True
    Check new dir + synced file: expect 2x True
    False True

**Comment by ezhov-evgeny** [comment]
@Zapnuk  I have tested the library with the Nextcloud and find out that Nextcload WebDAV does not support the method `HEAD` which is used by default for checking resources. 
You can use the `GET` method for the same purpose, below a configuration example with a method overriding for `check`: 

```python 
options = {
    'webdav_hostname': 'https://demo1.nextcloud.com/remote.php/dav/files/USERNAME/',
    'webdav_login': 'USERNAME',
    'webdav_password': 'PASSWORD',
    'webdav_override_methods': {
        'check': 'GET'
    }
}
```

**Comment by Zapnuk** [comment]
Thank you for the response. This resolved my issue.
