### ISSUE TITLE
Set `timeout` from input

### ISSUE THREAD

**Issue by fnattino** [ezhov-evgeny/webdav-client-python-3#67]
Hello! I am using `webdav-client-python-3` to talk to a WebDAV server - it's working really great! However, the hardcoded `timeout` value of 30 sec used in the HTTP requests is too short for my use case. Would it be possible to add the time out value as an optional setting to initialise the client? Thanks in advance!

**Comment by ezhov-evgeny** [comment]
Published

**Comment by ezhov-evgeny** [comment]
@fnattino For configuring a requests timeout you can use an option `webdav_timeout` with int value in seconds, by default the timeout is set to 30 seconds.

```
from webdav3.client import Client

options = {
 'webdav_hostname': "https://webdav.server.ru",
 'webdav_login':    "login",
 'webdav_password': "password",
 'webdav_timeout': 30
}
client = Client(options)
```

**Comment by fnattino** [comment]
@ezhov-evgeny Thanks a lot for the very fast reaction, that is really great!
