### ISSUE TITLE
ordering of directory contents

### ISSUE THREAD

**Issue by JOJ0** [ezhov-evgeny/webdav-client-python-3#72]
Hi again,
If I do something like this
```
client = Client(options)
all_files = client.list()
```
and then iterate through it, the ordering seems random. Is there a way to have the list method return it in a specific order (timestamp, filename, etc.) or is this not implemented (or even out of scope of your module)?
thanks!

**Comment by ezhov-evgeny** [comment]
@JOJ0 Hi,
WebDAV RFC-4918 doesn't support any options for defining a sorting.

So you can sort it in python code, for example by file name:
```python
client = Client(options)
sorted_files = client.list().sort()
```

Or if you use detailed list you can sort by another fields like timestamp:
```python
client = Client(options)
sorted_files = client.list(get_info=True).sort(key=lambda f: f['created'])
```

**Comment by JOJ0** [comment]
Perfect, thanks a lot!
