### ISSUE TITLE
download file get an empty file

### ISSUE THREAD

**Issue by huangganggui** [ezhov-evgeny/webdav-client-python-3#74]
HI, when I download file from webdav server with,   an empty file downloaded by `download_sync`. 

It is very difficult to reappear.  And I have a question about  [https://github.com/ezhov-evgeny/webdav-client-python-3/blob/09ae1414ddd331775686ebe55a625e732ef78b14/webdav3/client.py#L195](url) ,  Is it only when response.status_code == 507, == 404 , == 405, >= 400  raise exceptions? Is it possible  response other status_code when download file(GET)?  If other status_code come, [https://github.com/ezhov-evgeny/webdav-client-python-3/blob/09ae1414ddd331775686ebe55a625e732ef78b14/webdav3/client.py#L399](url) it may create an empty file but not write anything.   I don't know if that's the reason why I get an empty file.

**Comment by ezhov-evgeny** [comment]
@huangganggui You can enable DEBUG logging mode, then you will be able to see information about requests and responses. It helps us to understand what happens.

For enabling DEBUG mode in logging for example you can add following code in to your script:
```python
root = logging.getLogger()
root.setLevel(logging.DEBUG)

log_handler = logging.StreamHandler(sys.stdout)
log_handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
log_handler.setFormatter(formatter)
root.addHandler(log_handler)
```

**Comment by huangganggui** [comment]
Hi, It appear again.  

I use Nvidia Jetson Nano as a webdav client.
Steps:
1. download a file.
2.save file etag.
3. power off by remove power of Nvidia Jetson Nano
4. the etag of file saved succesfully, but the file downloaded saved error(empty file).

I guess the reason of empty file is that the OS has no enough time to save the file. And I have to do some operate like `sync` to save the file to disk or use `os.fsync()` to save the file .
